[package]
name = "libatmos"
version = "0.1.0"
authors = ["cyclowns <cyclowns@protonmail.ch>"]
edition = "2018"

[dependencies]
snafu = "0.4.4"
log = "0.4"
fern = "0.5.8"
chrono = "0.4.7"

[lib]
doctest = true

